name: LilyTran
favicon: null
layout_spectrum: 0.89981
typography_spectrum: 0.849376633297652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3125
  lightness: 0.8602289513219148
  saturation: 0.8267138623632491
  rhythmicContrast: 0.19032598659396172
purpose: []
