name: LilyTran
favicon: null
layout_spectrum: 0.89981
typography_spectrum: 0.849376633297652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7b7b7'
    - '#0c0b10'
    - '#4a4a4a'
    - '#e36861'
  brandStrength: 0.3125
  lightness: 0.8602289513219148
  saturation: 0.8267138623632491
  rhythmicContrast: 0.19032598659396172
purpose: []
